"use strict";
const $=id=>document.getElementById(id),KEY="lotto-helper-saved-v2",DATA_KEY="lotto-helper-imported-data",SETTINGS="lotto-helper-settings";let included=new Set(),current=[],draws=[],drawPage=0,deferredInstall=null;
const announce=m=>{const e=$("liveStatus");e.textContent="";setTimeout(()=>e.textContent=m,30)};const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function randomInt(max){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}function createNumbers(){const s=new Set(included);while(s.size<6)s.add(randomInt(45)+1);return[...s].sort((a,b)=>a-b)}
function readSaved(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}function writeSaved(v){localStorage.setItem(KEY,JSON.stringify(v));renderSaved();renderAdmin()}
function settings(){try{return JSON.parse(localStorage.getItem(SETTINGS)||"{}") }catch{return{}}}function saveSettings(p){localStorage.setItem(SETTINGS,JSON.stringify({...settings(),...p}))}
function ball(n,bonus=false){return `<span class="ball" aria-label="${bonus?"보너스 ":""}${n}번">${n}</span>`}function balls(nums,bonus){return `<div class="balls" aria-label="당첨번호 ${nums.join(", ")}${bonus?`, 보너스 ${bonus}`:""}">${nums.map(n=>ball(n)).join("")}${bonus?`<strong aria-hidden="true">+</strong>${ball(bonus,true)}`:""}</div>`}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function metric(label,value){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function initPicker(){const root=$("numberPicker");for(let n=1;n<=45;n++){const b=document.createElement("button");b.className="number-choice";b.textContent=n;b.dataset.number=n;b.setAttribute("aria-pressed","false");b.setAttribute("aria-label",`${n}번, 선택 안 됨`);b.addEventListener("click",()=>{if(included.has(n)){included.delete(n);b.setAttribute("aria-pressed","false");b.setAttribute("aria-label",`${n}번, 선택 안 됨`)}else if(included.size<6){included.add(n);b.setAttribute("aria-pressed","true");b.setAttribute("aria-label",`${n}번, 포함 번호로 선택됨`)}else return announce("포함 번호는 최대 6개입니다.");$("selectedCount").textContent=`${included.size}개`});root.append(b)}for(let n=1;n<=45;n++)$("pairNumber").add(new Option(`${n}번`,n))}
function validateCount(){const i=$("gameCount"),v=Number(i.value);let m="";if(i.value.trim()==="")m="게임 수를 입력해 주세요.";else if(!Number.isInteger(v))m="정수를 입력해 주세요.";else if(v<1)m="1게임 이상 입력해 주세요.";else if(v>100)m="최대 100게임까지 생성할 수 있습니다.";$("gameError").textContent=m;i.setAttribute("aria-invalid",String(!!m));return m?null:v}
function generate(){const count=validateCount();if(!count)return $("gameCount").focus();current=Array.from({length:count},createNumbers);const inc=[...included].sort((a,b)=>a-b),reason=inc.length?`포함 번호 ${inc.join(", ")}을(를) 넣고 나머지는 무작위로 생성했습니다.`:"1~45에서 무작위로 생성했습니다.";$("resultsList").innerHTML=current.map((g,i)=>`<article class="game"><h3>${i+1}게임</h3>${balls(g)}<p class="reason">${reason}</p></article>`).join("");$("resultSummary").textContent=`${count}게임 · 대상 ${$("targetRound").value||"미지정"}회`;$("resultsSection").hidden=false;announce(`${count}게임을 생성했습니다.`)}
function resultText(g=current){return["로또 번호 도우미 추천 번호",`대상 회차: ${$("targetRound").value||"미지정"}`,"",...g.map((x,i)=>`${i+1}게임: ${x.join(", ")}`),"","무작위 참고 번호이며 당첨을 보장하지 않습니다."].join("\n")}
async function copyText(t=resultText()){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement("textarea");a.value=t;document.body.append(a);a.select();document.execCommand("copy");a.remove()}announce("번호를 복사했습니다.")}
function saveCurrent(){if(!current.length)return;const list=readSaved();list.unshift({id:crypto.randomUUID?.()||String(Date.now()),created:new Date().toISOString(),round:Number($("targetRound").value)||null,games:current,included:[...included]});writeSaved(list.slice(0,100));announce("추천 번호를 저장했습니다.")}
function prize(nums,draw){if(!draw)return{label:"당첨번호 업데이트 전",className:"result-wait"};const hit=nums.filter(n=>draw.numbers.includes(n)),bonus=nums.includes(draw.bonus);let rank="낙첨";if(hit.length===6)rank="1등";else if(hit.length===5&&bonus)rank="2등";else if(hit.length===5)rank="3등";else if(hit.length===4)rank="4등";else if(hit.length===3)rank="5등";return{label:`${rank} · 일치 ${hit.length}개${bonus?" + 보너스":""}`,className:rank==="낙첨"?"result-none":"result-win"}}
function renderSaved(){const root=$("savedList"),list=readSaved();$("deleteAllButton").hidden=!list.length;if(!list.length){root.innerHTML='<p class="notice">저장한 번호가 없습니다.</p>';return}root.innerHTML=list.map(item=>{const draw=draws.find(d=>d.round===item.round);return `<article class="saved-item"><h3>${item.round?`${item.round}회`:"회차 미지정"} · ${new Date(item.created).toLocaleString("ko-KR")}</h3>${item.games.map((g,i)=>{const p=prize(g,draw);return `<div class="game ${p.className}"><strong>${i+1}게임</strong>${balls(g)}<p>${p.label}</p></div>`}).join("")}<div class="saved-actions"><button class="secondary saved-copy" data-id="${item.id}">복사</button><button class="danger saved-delete" data-id="${item.id}">삭제</button></div></article>`}).join("");root.querySelectorAll(".saved-copy").forEach(b=>b.onclick=()=>{const x=readSaved().find(i=>i.id===b.dataset.id);copyText(resultText(x.games))});root.querySelectorAll(".saved-delete").forEach(b=>b.onclick=()=>{if(confirm("이 저장 번호를 삭제하시겠습니까?"))writeSaved(readSaved().filter(i=>i.id!==b.dataset.id))})}
function normalizeDraw(x){return{round:Number(x.round??x.ltEpsd),date:String(x.date??x.ltRflYmd),numbers:(x.numbers??[x.tm1WnNo,x.tm2WnNo,x.tm3WnNo,x.tm4WnNo,x.tm5WnNo,x.tm6WnNo]).map(Number),bonus:Number(x.bonus??x.bnsWnNo),firstWinners:Number(x.firstWinners??x.rnk1WnNope??0),firstPrize:Number(x.firstPrize??x.rnk1WnAmt??0)}}
function validDraw(d){return Number.isInteger(d.round)&&d.numbers.length===6&&new Set(d.numbers).size===6&&d.numbers.every(n=>n>=1&&n<=45)&&d.bonus>=1&&d.bonus<=45&&!d.numbers.includes(d.bonus)}
async function loadDraws(){try{const imported=localStorage.getItem(DATA_KEY);let raw;if(imported)raw=JSON.parse(imported);else{const response=await fetch("data/draws.json",{cache:"no-store"});if(!response.ok)throw Error("data");raw=await response.json()}const list=Array.isArray(raw)?raw:raw.draws;draws=list.map(normalizeDraw).filter(validDraw).sort((a,b)=>b.round-a.round);if(!draws.length)throw Error("empty");const latest=draws[0];$("targetRound").value=latest.round+1;$("manualRound").value=latest.round;$("dataStatus").textContent=`${draws.length}개 회차 · 최신 ${latest.round}회`;$("dataFooter").textContent=`당첨번호 기준: ${latest.round}회 (${formatDate(latest.date)}) · 출처: 동행복권`;renderDraw(latest);renderDrawList();renderStats();renderSaved();renderAdmin();checkNewResults()}catch(e){$("dataStatus").textContent="당첨 데이터를 불러오지 못했습니다. 번호 추천은 계속 이용할 수 있습니다.";$("dataFooter").textContent="당첨 데이터 확인 필요";renderSaved();renderAdmin()}}
function formatDate(s){const t=String(s).replace(/\D/g,"");return t.length===8?`${t.slice(0,4)}-${t.slice(4,6)}-${t.slice(6)}`:s}
function renderDraw(d){if(!d){$("drawDetail").innerHTML='<p class="error">해당 회차를 찾을 수 없습니다.</p>';return}$("drawSearch").value=d.round;$("drawDetail").innerHTML=`<article class="draw-card"><h3>제${d.round}회 · ${formatDate(d.date)}</h3>${balls(d.numbers,d.bonus)}<p>1등 ${d.firstWinners.toLocaleString()}게임 · 1게임당 ${d.firstPrize.toLocaleString()}원</p></article>`}
function renderDrawList(){const pageSize=20,start=drawPage*pageSize,part=draws.slice(start,start+pageSize);$("drawList").innerHTML=table(["회차","추첨일","당첨번호","보너스"],part.map(d=>[d.round,formatDate(d.date),d.numbers.join(", "),d.bonus]));$("drawPageStatus").textContent=`${drawPage+1} / ${Math.max(1,Math.ceil(draws.length/pageSize))}쪽`;$("drawPrev").disabled=start+pageSize>=draws.length;$("drawNext").disabled=drawPage===0}
function bars(items){const max=Math.max(...items.map(x=>x[1]),1);return `<div class="bars">${items.map(([l,v])=>`<div class="bar-row"><span>${esc(l)}</span><div class="bar"><span style="width:${v/max*100}%"></span></div><strong>${v}</strong></div>`).join("")}</div>`}
function renderStats(){if(!draws.length)return;const val=$("statsRange").value,ds=val==="all"?draws:draws.slice(0,Number(val)),freq=Array(46).fill(0);ds.forEach(d=>d.numbers.forEach(n=>freq[n]++));const absence=[];for(let n=1;n<=45;n++)absence.push([n,draws.findIndex(d=>d.numbers.includes(n))]);const oddDist=new Map(),zones=[0,0,0,0,0],cons=new Map([["없음",0],["2개 연속",0],["3개 이상",0]]);ds.forEach(d=>{const odd=d.numbers.filter(n=>n%2).length;oddDist.set(`${odd}:${6-odd}`,1+(oddDist.get(`${odd}:${6-odd}`)||0));d.numbers.forEach(n=>zones[Math.min(4,Math.floor((n-1)/10))]++);let longest=1,run=1;for(let i=1;i<6;i++){run=d.numbers[i]===d.numbers[i-1]+1?run+1:1;longest=Math.max(longest,run)}const k=longest>=3?"3개 이상":longest===2?"2개 연속":"없음";cons.set(k,cons.get(k)+1)});const top=[...Array(45)].map((_,i)=>[i+1,freq[i+1]]).sort((a,b)=>b[1]-a[1]||a[0]-b[0]);const base=Number($("pairNumber").value||1),pairs=Array(46).fill(0);ds.filter(d=>d.numbers.includes(base)).forEach(d=>d.numbers.filter(n=>n!==base).forEach(n=>pairs[n]++));const pairTop=[...Array(45)].map((_,i)=>[i+1,pairs[i+1]]).filter(x=>x[0]!==base).sort((a,b)=>b[1]-a[1]||a[0]-b[0]).slice(0,10);$("statsSummary").innerHTML=metric("분석 회차",`${ds.length}회`)+metric("최다 출현",`${top[0][0]}번 · ${top[0][1]}회`)+metric("최장 미출현",`${absence.sort((a,b)=>b[1]-a[1])[0][0]}번 · ${absence[0][1]}회`)+metric("연속번호 회차",`${cons.get("2개 연속")+cons.get("3개 이상")}회`);$("frequencyTable").innerHTML=table(["번호","출현 횟수"],top.map(x=>[x[0],x[1]]));$("absenceTable").innerHTML=table(["번호","최근 미출현"],absence.sort((a,b)=>b[1]-a[1]).map(x=>[x[0],x[1]<0?"범위 내 없음":`${x[1]}회`]));$("oddEvenTable").innerHTML=bars([...oddDist.entries()].sort().map(([k,v])=>[`홀:짝 ${k}`,v]));$("zoneTable").innerHTML=bars([["1~10",zones[0]],["11~20",zones[1]],["21~30",zones[2]],["31~40",zones[3]],["41~45",zones[4]]]);$("consecutiveTable").innerHTML=bars([...cons.entries()]);$("pairTable").innerHTML=`<p>${base}번과 같은 회차에 나온 횟수</p>${bars(pairTop.map(x=>[`${x[0]}번`,x[1]]))}`}
function renderAdmin(){$("adminMetrics").innerHTML=metric("당첨 데이터",`${draws.length}회`)+metric("최신 회차",draws[0]?`${draws[0].round}회`:"없음")+metric("저장 기록",`${readSaved().length}개`)+metric("데이터 출처","동행복권")}
function manualCheck(){const round=Number($("manualRound").value),nums=($("manualNumbers").value.match(/\d+/g)||[]).map(Number),draw=draws.find(d=>d.round===round);if(nums.length!==6||new Set(nums).size!==6||nums.some(n=>n<1||n>45))return $("manualResult").innerHTML='<p class="error">1~45의 서로 다른 번호 6개를 입력해 주세요.</p>';const p=prize(nums,draw);$("manualResult").innerHTML=`<article class="draw-card ${p.className}"><h3>${round}회 확인 결과</h3>${balls(nums)}<p class="rank">${p.label}</p><p>공식 홈페이지 또는 판매점에서 최종 확인하세요.</p></article>`}
function download(name,obj){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function importJson(file,type){try{const raw=JSON.parse(await file.text());if(type==="data"){const list=(Array.isArray(raw)?raw:raw.draws).map(normalizeDraw);if(!list.length||!list.every(validDraw))throw Error();localStorage.setItem(DATA_KEY,JSON.stringify(list));await loadDraws()}else{if(!Array.isArray(raw))throw Error();writeSaved(raw)}announce("데이터를 가져왔습니다.")}catch{announce("올바른 JSON 파일이 아닙니다.")}}
function speak(){if(!speechSynthesis)return announce("음성 읽기를 지원하지 않습니다.");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.map((g,i)=>`${i+1}게임은 ${g.join(", ")}입니다.`).join(" "));u.lang="ko-KR";u.rate=Number($("speechRate").value);u.onstart=()=>$("stopSpeakButton").disabled=false;u.onend=()=>$("stopSpeakButton").disabled=true;speechSynthesis.speak(u)}
async function share(){if(navigator.share)try{return await navigator.share({title:"로또 번호 도우미",text:resultText()})}catch(e){if(e.name==="AbortError")return}copyText()}
function saveImage(){const w=720,h=180+current.length*62,c=document.createElement("canvas");c.width=w*2;c.height=h*2;const x=c.getContext("2d");x.scale(2,2);x.fillStyle="#f4f7fb";x.fillRect(0,0,w,h);x.fillStyle="#172033";x.font="bold 30px Malgun Gothic";x.fillText("로또 번호 도우미",35,48);x.font="16px Malgun Gothic";x.fillText(`대상 ${$("targetRound").value||"미지정"}회`,35,78);current.forEach((g,i)=>{const y=125+i*62;x.font="bold 16px Malgun Gothic";x.fillStyle="#172033";x.fillText(`${i+1}게임`,35,y);g.forEach((n,j)=>{const cx=145+j*82;x.beginPath();x.fillStyle="#155eef";x.arc(cx,y-6,24,0,Math.PI*2);x.fill();x.fillStyle="#fff";x.textAlign="center";x.fillText(n,cx,y);x.textAlign="left"})});x.fillStyle="#59657a";x.fillText("무작위 참고 번호이며 당첨을 보장하지 않습니다.",35,h-25);const a=document.createElement("a");a.download="로또_추천번호.png";a.href=c.toDataURL();a.click()}
async function notification(){if(!("Notification"in window))return announce("알림을 지원하지 않습니다.");const p=await Notification.requestPermission();saveSettings({notifications:p==="granted"});announce(p==="granted"?"알림을 사용합니다.":"알림이 허용되지 않았습니다.")}
function checkNewResults(){const s=settings(),latest=draws[0]?.round||0;if(s.notifications&&Notification.permission==="granted"&&latest>(s.lastNotified||0)){const checked=readSaved().filter(x=>x.round===latest).flatMap(x=>x.games.map(g=>prize(g,draws[0]).label));new Notification(`제${latest}회 당첨번호가 등록되었습니다.`,{body:checked.length?`저장 번호 ${checked.length}게임을 확인했습니다. 앱에서 결과를 확인하세요.`:"최신 당첨번호를 확인하세요."});saveSettings({lastNotified:latest})}}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>{x.classList.toggle("active",x===b);x.removeAttribute("aria-current")});b.setAttribute("aria-current","page");document.querySelectorAll(".view").forEach(v=>{v.hidden=v.id!==`view-${b.dataset.view}`;v.classList.toggle("active",!v.hidden)});if(b.dataset.view==="stats")renderStats();if(b.dataset.view==="saved")renderSaved();$("main").focus()});$("generateButton").onclick=generate;$("regenerateButton").onclick=generate;$("gameCount").oninput=validateCount;$("clearIncluded").onclick=()=>{included.clear();document.querySelectorAll(".number-choice").forEach((b,i)=>{b.setAttribute("aria-pressed","false");b.setAttribute("aria-label",`${i+1}번, 선택 안 됨`)});$("selectedCount").textContent="0개"};$("saveButton").onclick=saveCurrent;$("copyButton").onclick=()=>copyText();$("shareButton").onclick=share;$("imageButton").onclick=saveImage;$("speakButton").onclick=speak;$("stopSpeakButton").onclick=()=>{speechSynthesis.cancel();$("stopSpeakButton").disabled=true};$("drawSearchButton").onclick=()=>renderDraw(draws.find(d=>d.round===Number($("drawSearch").value)));$("latestDrawButton").onclick=()=>renderDraw(draws[0]);$("drawPrev").onclick=()=>{drawPage++;renderDrawList()};$("drawNext").onclick=()=>{drawPage=Math.max(0,drawPage-1);renderDrawList()};$("refreshStats").onclick=renderStats;$("statsRange").onchange=renderStats;$("pairNumber").onchange=renderStats;$("manualCheckButton").onclick=manualCheck;$("deleteAllButton").onclick=()=>{if(confirm("저장 번호를 모두 삭제하시겠습니까?"))writeSaved([])};$("exportDataButton").onclick=()=>download("draws.json",{updatedAt:new Date().toISOString(),source:"동행복권",draws});$("exportSavedButton").onclick=()=>download("saved-numbers.json",readSaved());$("importDataInput").onchange=e=>e.target.files[0]&&importJson(e.target.files[0],"data");$("importSavedInput").onchange=e=>e.target.files[0]&&importJson(e.target.files[0],"saved");$("notificationButton").onclick=notification;$("speechRate").oninput=e=>{$("speechRateValue").textContent=`${e.target.value}배`;saveSettings({speechRate:e.target.value})};$("textSizeButton").onclick=e=>toggleSetting("large-text",e.currentTarget,"글자 크게","글자 원래대로");$("contrastButton").onclick=e=>toggleSetting("high-contrast",e.currentTarget,"고대비","일반 화면");$("clearAppData").onclick=()=>{if(confirm("이 기기의 저장 번호와 설정을 모두 삭제하시겠습니까?")){[KEY,DATA_KEY,SETTINGS].forEach(k=>localStorage.removeItem(k));location.reload()}};$("installButton").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("installButton").hidden=true}}}
function toggleSetting(cls,b,onLabel,offLabel){const on=document.documentElement.classList.toggle(cls);b.setAttribute("aria-pressed",String(on));b.textContent=on?offLabel:onLabel;saveSettings({[cls]:on});announce(`${onLabel} 설정을 ${on?"켰습니다":"껐습니다"}.`)}
function initSettings(){const s=settings();["large-text","high-contrast"].forEach(cls=>document.documentElement.classList.toggle(cls,!!s[cls]));$("textSizeButton").textContent=s["large-text"]?"글자 원래대로":"글자 크게";$("contrastButton").textContent=s["high-contrast"]?"일반 화면":"고대비";$("speechRate").value=s.speechRate||.9;$("speechRateValue").textContent=`${$("speechRate").value}배`}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("installButton").hidden=false});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));initPicker();initSettings();bind();loadDraws();
