"use strict";
const $=id=>document.getElementById(id);const STORAGE_KEY="lotto-helper-saved-v1";let included=new Set(),current=[];
const picker=$("numberPicker"),live=$("liveStatus"),resultsSection=$("resultsSection"),resultsList=$("resultsList");
function announce(message){live.textContent="";setTimeout(()=>live.textContent=message,30)}
function randomInt(max){const values=new Uint32Array(1);crypto.getRandomValues(values);return values[0]%max}
function createNumbers(){const nums=new Set(included);while(nums.size<6)nums.add(randomInt(45)+1);return [...nums].sort((a,b)=>a-b)}
function buildPicker(){for(let n=1;n<=45;n++){const b=document.createElement("button");b.type="button";b.className="number-choice";b.textContent=n;b.dataset.number=n;b.setAttribute("aria-pressed","false");b.setAttribute("aria-label",`${n}번, 선택 안 됨`);b.addEventListener("click",()=>toggleNumber(b,n));picker.append(b)}}
function toggleNumber(button,n){if(included.has(n)){included.delete(n);button.setAttribute("aria-pressed","false");button.setAttribute("aria-label",`${n}번, 선택 안 됨`)}else{if(included.size>=6){announce("포함할 번호는 최대 6개까지 선택할 수 있습니다.");return}included.add(n);button.setAttribute("aria-pressed","true");button.setAttribute("aria-label",`${n}번, 포함 번호로 선택됨`)}$("selectedCount").textContent=`${included.size}개`}
function validateCount(){const input=$("gameCount"),value=Number(input.value),error=$("gameError");let message="";if(input.value.trim()==="")message="생성할 게임 수를 입력해 주세요.";else if(!Number.isInteger(value))message="게임 수는 정수로 입력해 주세요.";else if(value<1)message="게임 수는 1 이상이어야 합니다.";else if(value>100)message="한 번에 최대 100게임까지 생성할 수 있습니다.";error.textContent=message;input.setAttribute("aria-invalid",String(Boolean(message)));return message?null:value}
function reason(){const nums=[...included].sort((a,b)=>a-b);return nums.length?`포함 번호 ${nums.join(", ")}을(를) 넣고 나머지는 무작위로 생성했습니다.`:"1부터 45까지의 번호 중 무작위로 생성했습니다."}
function ball(n){const span=document.createElement("span");span.className="ball";span.textContent=n;span.setAttribute("aria-label",`${n}번`);return span}
function renderResults(){resultsList.replaceChildren();current.forEach((nums,i)=>{const article=document.createElement("article");article.className="game";const h=document.createElement("h3");h.textContent=`${i+1}게임`;const balls=document.createElement("div");balls.className="balls";balls.setAttribute("aria-label",`${i+1}게임 추천 번호 ${nums.join(", ")}`);nums.forEach(n=>balls.append(ball(n)));const p=document.createElement("p");p.className="reason";p.textContent=reason();article.append(h,balls,p);resultsList.append(article)});$("resultSummary").textContent=`${current.length}게임을 생성했습니다.`;resultsSection.hidden=false}
function generate(){const count=validateCount();if(!count){$("gameCount").focus();return}current=Array.from({length:count},createNumbers);renderResults();resultsSection.scrollIntoView({behavior:"smooth",block:"start"});announce(`${count}게임의 추천 번호가 생성되었습니다. 결과 영역에서 확인하거나 음성으로 들을 수 있습니다.`)}
function resultText(games=current){return ["로또 번호 도우미 추천 번호","",...games.map((n,i)=>`${i+1}게임: ${n.join(", ")}`),"",`생성일: ${new Date().toLocaleString("ko-KR")}`,"※ 무작위 추천 번호이며 당첨을 보장하지 않습니다."].join("\n")}
async function copyText(text=resultText()){try{await navigator.clipboard.writeText(text);announce("추천 번호를 클립보드에 복사했습니다.")}catch{const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();announce("추천 번호를 클립보드에 복사했습니다.")}}
function readSaved(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function writeSaved(items){localStorage.setItem(STORAGE_KEY,JSON.stringify(items));renderSaved()}
function saveCurrent(){if(!current.length)return;const items=readSaved();items.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),created:new Date().toISOString(),games:current,included:[...included]});writeSaved(items.slice(0,50));announce("추천 번호를 이 브라우저에 저장했습니다.")}
function renderSaved(){const root=$("savedList"),items=readSaved();root.replaceChildren();$("deleteAllButton").hidden=!items.length;if(!items.length){const p=document.createElement("p");p.className="empty";p.textContent="아직 저장한 번호가 없습니다.";root.append(p);return}items.forEach(item=>{const el=document.createElement("article");el.className="saved-item";const h=document.createElement("h3");h.textContent=new Date(item.created).toLocaleString("ko-KR");const p=document.createElement("p");p.textContent=item.games.map((g,i)=>`${i+1}게임: ${g.join(", ")}`).join(" / ");const actions=document.createElement("div");actions.className="saved-actions";const copy=document.createElement("button");copy.className="secondary";copy.type="button";copy.textContent="이 번호 복사";copy.addEventListener("click",()=>copyText(resultText(item.games)));const del=document.createElement("button");del.className="danger";del.type="button";del.textContent="이 번호 삭제";del.addEventListener("click",()=>{if(confirm("저장한 추천 번호를 삭제하시겠습니까? 삭제한 번호는 복구할 수 없습니다.")){writeSaved(readSaved().filter(x=>x.id!==item.id));announce("저장한 번호를 삭제했습니다.")}});actions.append(copy,del);el.append(h,p,actions);root.append(el)})}
function speak(){if(!("speechSynthesis" in window)){announce("이 브라우저에서는 음성 읽기를 지원하지 않습니다.");return}speechSynthesis.cancel();const text=current.map((g,i)=>`${i+1}게임 추천 번호는 ${g.join(", ")}입니다.`).join(" ");const u=new SpeechSynthesisUtterance(text);u.lang="ko-KR";u.rate=.9;u.onstart=()=>{$("stopSpeakButton").disabled=false;announce("추천 번호 음성 읽기를 시작합니다.")};u.onend=()=>{$("stopSpeakButton").disabled=true;announce("추천 번호 음성 읽기가 끝났습니다.")};speechSynthesis.speak(u)}
async function share(){const text=resultText();if(navigator.share){try{await navigator.share({title:"로또 번호 도우미 추천 번호",text});announce("추천 번호를 공유했습니다.");return}catch(e){if(e.name==="AbortError")return}}await copyText(text);announce("공유 기능을 사용할 수 없어 추천 번호를 복사했습니다.")}
function saveImage(){const scale=2,w=720,row=66,h=190+current.length*row;const c=document.createElement("canvas");c.width=w*scale;c.height=h*scale;const x=c.getContext("2d");x.scale(scale,scale);x.fillStyle="#f4f7fb";x.fillRect(0,0,w,h);x.fillStyle="#172033";x.font="bold 30px Malgun Gothic";x.fillText("로또 번호 도우미",40,55);x.font="16px Malgun Gothic";x.fillText(new Date().toLocaleString("ko-KR"),40,85);current.forEach((g,i)=>{const y=135+i*row;x.font="bold 17px Malgun Gothic";x.fillStyle="#172033";x.fillText(`${i+1}게임`,40,y+18);g.forEach((n,j)=>{const cx=155+j*82;x.beginPath();x.fillStyle="#155eef";x.arc(cx,y+10,25,0,Math.PI*2);x.fill();x.fillStyle="#fff";x.textAlign="center";x.font="bold 17px Malgun Gothic";x.fillText(n,cx,y+16)});x.textAlign="left"});x.fillStyle="#59657a";x.font="14px Malgun Gothic";x.fillText("무작위 추천 번호이며 당첨을 보장하지 않습니다.",40,h-30);const a=document.createElement("a");a.download=`로또_추천번호_${new Date().toISOString().slice(0,10)}.png`;a.href=c.toDataURL("image/png");a.click();announce("추천 결과 이미지를 저장했습니다.")}
function toggleSetting(cls,button,labelOn,labelOff){const on=document.documentElement.classList.toggle(cls);button.setAttribute("aria-pressed",String(on));button.textContent=on?labelOff:labelOn;localStorage.setItem(`setting-${cls}`,String(on));announce(on?`${labelOn} 설정을 켰습니다.`:`${labelOn} 설정을 껐습니다.`)}
buildPicker();renderSaved();["large-text","high-contrast"].forEach(cls=>{if(localStorage.getItem(`setting-${cls}`)==="true")document.documentElement.classList.add(cls)});$("textSizeButton").setAttribute("aria-pressed",String(document.documentElement.classList.contains("large-text")));$("textSizeButton").textContent=document.documentElement.classList.contains("large-text")?"글자 원래대로":"글자 크게";$("contrastButton").setAttribute("aria-pressed",String(document.documentElement.classList.contains("high-contrast")));$("contrastButton").textContent=document.documentElement.classList.contains("high-contrast")?"일반 화면":"고대비";
$("generateButton").addEventListener("click",generate);$("regenerateButton").addEventListener("click",generate);$("gameCount").addEventListener("input",validateCount);$("clearIncluded").addEventListener("click",()=>{included.clear();picker.querySelectorAll("button").forEach((b,i)=>{b.setAttribute("aria-pressed","false");b.setAttribute("aria-label",`${i+1}번, 선택 안 됨`)});$("selectedCount").textContent="0개";announce("선택한 포함 번호를 모두 해제했습니다.")});$("copyButton").addEventListener("click",()=>copyText());$("saveButton").addEventListener("click",saveCurrent);$("speakButton").addEventListener("click",speak);$("stopSpeakButton").addEventListener("click",()=>{speechSynthesis.cancel();$("stopSpeakButton").disabled=true;announce("음성 읽기를 중지했습니다.")});$("shareButton").addEventListener("click",share);$("imageButton").addEventListener("click",saveImage);$("deleteAllButton").addEventListener("click",()=>{if(confirm("저장한 번호를 모두 삭제하시겠습니까? 삭제한 번호는 복구할 수 없습니다.")){writeSaved([]);announce("저장한 번호를 모두 삭제했습니다.")}});$("textSizeButton").addEventListener("click",e=>toggleSetting("large-text",e.currentTarget,"글자 크게","글자 원래대로"));$("contrastButton").addEventListener("click",e=>toggleSetting("high-contrast",e.currentTarget,"고대비","일반 화면"));
